
# YAML config file for cache simulator

general:
  word_size: 4 #bytes
  block_size: 16 #bytes
  write_back: true

cache1: #required
  blocks: 16
  associativity: 1
  hit_time: 1 #cycles

memory: #required
  hit_time: 1000 #cycles

cache:
    L1:
        blocks: 16
        associativity: 1
        hit_time: 1
