
# YAML config file for cache simulator

general:
  word_size: 4 #bytes
  block_size: 16 #bytes
  write_back: true

L1: #required
  blocks: 16
  associativity: 1
  latency: 1 #cycles

memory: #required
  latency: 1000 #cycles
